version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    ports:
      - 8080:8080
    environment: 
      - URLS_PRIMARY_NAME=Items
      - URLS=[{name:'Items', url:'docs/items/items.swagger.json'},{name:'Accounts', url:'docs/accounts/accounts.swagger.json'}]
    volumes:
      - .:/usr/share/nginx/html/docs/